INFO     ApiClient:api_client.py:93 Request: POST https://dev-gs.qa-playground.com/api/v1/users | Headers: {'Authorization': 'Bearer qahack2024:ilyastetsun@gmail.com', 'Accept': 'application/json', 'X-Task-Id': 'api-7'}
INFO     ApiClient:api_client.py:95 Response [409]: {"code":409,"message":"User with the following \"email\" already exists: d4@l.66d"}

INFO     ApiClient:api_client.py:139 Request: POST https://dev-gs.qa-playground.com/api/v1/users/login | Headers: {'Authorization': 'Bearer qahack2024:ilyastetsun@gmail.com', 'Accept': 'application/json', 'X-Task-Id': 'api-7'}
INFO     ApiClient:api_client.py:141 Response [404]: {"code":404,"message":"Could not find user with given credentials"}