{"uid":"ee798a145046cc4f","name":"test_validate_payment[api-19]","fullName":"tests.endpoints.test_payments#test_validate_payment","historyId":"5dad880742ddfd39d1015f29f76581bb","time":{"start":1733084995786,"stop":1733084999236,"duration":3450},"status":"failed","statusMessage":"AssertionError: Response validation failed: 2 validation errors for PaymentResponse\n  created_at\n    Field required [type=missing, input_value={'amount': 5999, 'order_u...4265-828d-6509050a18e8'}, input_type=dict]\n      For further information visit https://errors.pydantic.dev/2.9/v/missing\n  updated_at\n    Field required [type=missing, input_value={'amount': 5999, 'order_u...4265-828d-6509050a18e8'}, input_type=dict]\n      For further information visit https://errors.pydantic.dev/2.9/v/missing\nassert False","statusTrace":"api_client = <api_handler.api_client.ApiClient object at 0x7f7e012f8c50>\nx_task_value = 'api-19'\n\n    @allure.feature(\"Orders API\")\n    @allure.story(\"Duplicate item in order\")\n    @pytest.mark.parametrize(\"x_task_value\", [\"api-19\"])\n    def test_validate_payment(api_client, x_task_value):\n        users_response = api_client.get_users(x_task_value, 0)\n        users_dto = Users(**users_response.json())\n    \n        user_uuid = users_dto.users[0].uuid\n    \n        games = api_client.get_games(x_task_value)\n        games_dto = GamesResponse(**games.json())\n        game_uuid = games_dto.games[0].uuid\n    \n        order_data = OrderItemList(items=[\n            OrderItem(item_uuid=game_uuid, quantity=1)\n        ])\n    \n        create_order = api_client.order_create(user_uuid, order_data.model_dump(), x_task_value)\n        orders = Order(**create_order.json())\n        order_uuid = orders.uuid\n    \n        payment = PaymentRequest(order_uuid=order_uuid, payment_method=\"card\")\n    \n        payment_response = api_client.create_payment(user_uuid, payment, x_task_value)\n        payment = PaymentResponse(**payment_response.json())\n        get_payments = api_client.get_payment(payment.uuid, x_task_value)\n    \n        try:\n>           PaymentResponse(**get_payments.json())\nE           pydantic_core._pydantic_core.ValidationError: 2 validation errors for PaymentResponse\nE           created_at\nE             Field required [type=missing, input_value={'amount': 5999, 'order_u...4265-828d-6509050a18e8'}, input_type=dict]\nE               For further information visit https://errors.pydantic.dev/2.9/v/missing\nE           updated_at\nE             Field required [type=missing, input_value={'amount': 5999, 'order_u...4265-828d-6509050a18e8'}, input_type=dict]\nE               For further information visit https://errors.pydantic.dev/2.9/v/missing\n\ntests/endpoints/test_payments.py:37: ValidationError\n\nDuring handling of the above exception, another exception occurred:\n\napi_client = <api_handler.api_client.ApiClient object at 0x7f7e012f8c50>\nx_task_value = 'api-19'\n\n    @allure.feature(\"Orders API\")\n    @allure.story(\"Duplicate item in order\")\n    @pytest.mark.parametrize(\"x_task_value\", [\"api-19\"])\n    def test_validate_payment(api_client, x_task_value):\n        users_response = api_client.get_users(x_task_value, 0)\n        users_dto = Users(**users_response.json())\n    \n        user_uuid = users_dto.users[0].uuid\n    \n        games = api_client.get_games(x_task_value)\n        games_dto = GamesResponse(**games.json())\n        game_uuid = games_dto.games[0].uuid\n    \n        order_data = OrderItemList(items=[\n            OrderItem(item_uuid=game_uuid, quantity=1)\n        ])\n    \n        create_order = api_client.order_create(user_uuid, order_data.model_dump(), x_task_value)\n        orders = Order(**create_order.json())\n        order_uuid = orders.uuid\n    \n        payment = PaymentRequest(order_uuid=order_uuid, payment_method=\"card\")\n    \n        payment_response = api_client.create_payment(user_uuid, payment, x_task_value)\n        payment = PaymentResponse(**payment_response.json())\n        get_payments = api_client.get_payment(payment.uuid, x_task_value)\n    \n        try:\n            PaymentResponse(**get_payments.json())\n        except ValidationError as e:\n            print(\"ValidationError:\", e)\n>           assert False, f\"Response validation failed: {e}\"\nE           AssertionError: Response validation failed: 2 validation errors for PaymentResponse\nE             created_at\nE               Field required [type=missing, input_value={'amount': 5999, 'order_u...4265-828d-6509050a18e8'}, input_type=dict]\nE                 For further information visit https://errors.pydantic.dev/2.9/v/missing\nE             updated_at\nE               Field required [type=missing, input_value={'amount': 5999, 'order_u...4265-828d-6509050a18e8'}, input_type=dict]\nE                 For further information visit https://errors.pydantic.dev/2.9/v/missing\nE           assert False\n\ntests/endpoints/test_payments.py:40: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1733084982873,"stop":1733084982874,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"base_url","time":{"start":1733084982874,"stop":1733084982874,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"worker_id","time":{"start":1733084982875,"stop":1733084982875,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"setup_test","time":{"start":1733084982875,"stop":1733084985487,"duration":2612},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"api_client","time":{"start":1733084982875,"stop":1733084982875,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"failed","statusMessage":"AssertionError: Response validation failed: 2 validation errors for PaymentResponse\n  created_at\n    Field required [type=missing, input_value={'amount': 5999, 'order_u...4265-828d-6509050a18e8'}, input_type=dict]\n      For further information visit https://errors.pydantic.dev/2.9/v/missing\n  updated_at\n    Field required [type=missing, input_value={'amount': 5999, 'order_u...4265-828d-6509050a18e8'}, input_type=dict]\n      For further information visit https://errors.pydantic.dev/2.9/v/missing\nassert False","statusTrace":"api_client = <api_handler.api_client.ApiClient object at 0x7f7e012f8c50>\nx_task_value = 'api-19'\n\n    @allure.feature(\"Orders API\")\n    @allure.story(\"Duplicate item in order\")\n    @pytest.mark.parametrize(\"x_task_value\", [\"api-19\"])\n    def test_validate_payment(api_client, x_task_value):\n        users_response = api_client.get_users(x_task_value, 0)\n        users_dto = Users(**users_response.json())\n    \n        user_uuid = users_dto.users[0].uuid\n    \n        games = api_client.get_games(x_task_value)\n        games_dto = GamesResponse(**games.json())\n        game_uuid = games_dto.games[0].uuid\n    \n        order_data = OrderItemList(items=[\n            OrderItem(item_uuid=game_uuid, quantity=1)\n        ])\n    \n        create_order = api_client.order_create(user_uuid, order_data.model_dump(), x_task_value)\n        orders = Order(**create_order.json())\n        order_uuid = orders.uuid\n    \n        payment = PaymentRequest(order_uuid=order_uuid, payment_method=\"card\")\n    \n        payment_response = api_client.create_payment(user_uuid, payment, x_task_value)\n        payment = PaymentResponse(**payment_response.json())\n        get_payments = api_client.get_payment(payment.uuid, x_task_value)\n    \n        try:\n>           PaymentResponse(**get_payments.json())\nE           pydantic_core._pydantic_core.ValidationError: 2 validation errors for PaymentResponse\nE           created_at\nE             Field required [type=missing, input_value={'amount': 5999, 'order_u...4265-828d-6509050a18e8'}, input_type=dict]\nE               For further information visit https://errors.pydantic.dev/2.9/v/missing\nE           updated_at\nE             Field required [type=missing, input_value={'amount': 5999, 'order_u...4265-828d-6509050a18e8'}, input_type=dict]\nE               For further information visit https://errors.pydantic.dev/2.9/v/missing\n\ntests/endpoints/test_payments.py:37: ValidationError\n\nDuring handling of the above exception, another exception occurred:\n\napi_client = <api_handler.api_client.ApiClient object at 0x7f7e012f8c50>\nx_task_value = 'api-19'\n\n    @allure.feature(\"Orders API\")\n    @allure.story(\"Duplicate item in order\")\n    @pytest.mark.parametrize(\"x_task_value\", [\"api-19\"])\n    def test_validate_payment(api_client, x_task_value):\n        users_response = api_client.get_users(x_task_value, 0)\n        users_dto = Users(**users_response.json())\n    \n        user_uuid = users_dto.users[0].uuid\n    \n        games = api_client.get_games(x_task_value)\n        games_dto = GamesResponse(**games.json())\n        game_uuid = games_dto.games[0].uuid\n    \n        order_data = OrderItemList(items=[\n            OrderItem(item_uuid=game_uuid, quantity=1)\n        ])\n    \n        create_order = api_client.order_create(user_uuid, order_data.model_dump(), x_task_value)\n        orders = Order(**create_order.json())\n        order_uuid = orders.uuid\n    \n        payment = PaymentRequest(order_uuid=order_uuid, payment_method=\"card\")\n    \n        payment_response = api_client.create_payment(user_uuid, payment, x_task_value)\n        payment = PaymentResponse(**payment_response.json())\n        get_payments = api_client.get_payment(payment.uuid, x_task_value)\n    \n        try:\n            PaymentResponse(**get_payments.json())\n        except ValidationError as e:\n            print(\"ValidationError:\", e)\n>           assert False, f\"Response validation failed: {e}\"\nE           AssertionError: Response validation failed: 2 validation errors for PaymentResponse\nE             created_at\nE               Field required [type=missing, input_value={'amount': 5999, 'order_u...4265-828d-6509050a18e8'}, input_type=dict]\nE                 For further information visit https://errors.pydantic.dev/2.9/v/missing\nE             updated_at\nE               Field required [type=missing, input_value={'amount': 5999, 'order_u...4265-828d-6509050a18e8'}, input_type=dict]\nE                 For further information visit https://errors.pydantic.dev/2.9/v/missing\nE           assert False\n\ntests/endpoints/test_payments.py:40: AssertionError","steps":[],"attachments":[{"uid":"23edf97b2a0dde5b","name":"log","source":"23edf97b2a0dde5b.txt","type":"text/plain","size":5160},{"uid":"3e4c051cad369a5","name":"stdout","source":"3e4c051cad369a5.txt","type":"text/plain","size":461},{"uid":"1552bf4b1513b781","name":"stderr","source":"1552bf4b1513b781.txt","type":"text/plain","size":5124}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":3,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"setup_test::0","time":{"start":1733084999241,"stop":1733084999241,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"story","value":"Duplicate item in order"},{"name":"feature","value":"Orders API"},{"name":"parentSuite","value":"tests.endpoints"},{"name":"suite","value":"test_payments"},{"name":"host","value":"fv-az881-610"},{"name":"thread","value":"2818-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.endpoints.test_payments"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"x_task_value","value":"'api-19'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":2,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":3},"items":[{"uid":"6ed1ab9322b0b8f8","reportUrl":"https://ils-808.github.io/qahack/61//#testresult/6ed1ab9322b0b8f8","status":"failed","statusDetails":"AssertionError: Response validation failed: 2 validation errors for PaymentResponse\n  created_at\n    Field required [type=missing, input_value={'amount': 5999, 'order_u...4b6a-b741-61e0f653a32b'}, input_type=dict]\n      For further information visit https://errors.pydantic.dev/2.9/v/missing\n  updated_at\n    Field required [type=missing, input_value={'amount': 5999, 'order_u...4b6a-b741-61e0f653a32b'}, input_type=dict]\n      For further information visit https://errors.pydantic.dev/2.9/v/missing\nassert False","time":{"start":1733084774245,"stop":1733084778068,"duration":3823}},{"uid":"1cdc5125ef3203b2","reportUrl":"https://ils-808.github.io/qahack/60//#testresult/1cdc5125ef3203b2","status":"passed","time":{"start":1733084495967,"stop":1733084500412,"duration":4445}}]},"tags":[]},"source":"ee798a145046cc4f.json","parameterValues":["'api-19'"]}