{"uid":"2d1c196d4ca64ec8","name":"test_change_order_status[canceled-api-18]","fullName":"tests.endpoints.test_orders#test_change_order_status","historyId":"64a9041c793eaa2bb9f015ab6b096f49","time":{"start":1733072747101,"stop":1733072748695,"duration":1594},"status":"broken","statusMessage":"pydantic_core._pydantic_core.ValidationError: 2 validation errors for Users\nusers\n  Field required [type=missing, input_value={'code': 500, 'message': 'Internal server error'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.9/v/missing\nmeta\n  Field required [type=missing, input_value={'code': 500, 'message': 'Internal server error'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.9/v/missing","statusTrace":"api_client = <api_handler.ApiClient.ApiClient object at 0x7f22d3899490>\nstatus = 'canceled', x_task_value = 'api-18'\n\n    @allure.feature(\"Orders API\")\n    @allure.story(\"Change order status\")\n    @pytest.mark.parametrize(\"status, x_task_value\", [(\"canceled\", \"api-18\")])\n    def test_change_order_status(api_client, status, x_task_value):\n        users_response = api_client.get_users(x_task_value, 0)\n>       users_dto = Users(**users_response.json())\nE       pydantic_core._pydantic_core.ValidationError: 2 validation errors for Users\nE       users\nE         Field required [type=missing, input_value={'code': 500, 'message': 'Internal server error'}, input_type=dict]\nE           For further information visit https://errors.pydantic.dev/2.9/v/missing\nE       meta\nE         Field required [type=missing, input_value={'code': 500, 'message': 'Internal server error'}, input_type=dict]\nE           For further information visit https://errors.pydantic.dev/2.9/v/missing\n\ntests/endpoints/test_orders.py:60: ValidationError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"pydantic_core._pydantic_core.ValidationError: 2 validation errors for Users\nusers\n  Field required [type=missing, input_value={'code': 500, 'message': 'Internal server error'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.9/v/missing\nmeta\n  Field required [type=missing, input_value={'code': 500, 'message': 'Internal server error'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.9/v/missing","statusTrace":"api_client = <api_handler.ApiClient.ApiClient object at 0x7f22d3899490>\nstatus = 'canceled', x_task_value = 'api-18'\n\n    @allure.feature(\"Orders API\")\n    @allure.story(\"Change order status\")\n    @pytest.mark.parametrize(\"status, x_task_value\", [(\"canceled\", \"api-18\")])\n    def test_change_order_status(api_client, status, x_task_value):\n        users_response = api_client.get_users(x_task_value, 0)\n>       users_dto = Users(**users_response.json())\nE       pydantic_core._pydantic_core.ValidationError: 2 validation errors for Users\nE       users\nE         Field required [type=missing, input_value={'code': 500, 'message': 'Internal server error'}, input_type=dict]\nE           For further information visit https://errors.pydantic.dev/2.9/v/missing\nE       meta\nE         Field required [type=missing, input_value={'code': 500, 'message': 'Internal server error'}, input_type=dict]\nE           For further information visit https://errors.pydantic.dev/2.9/v/missing\n\ntests/endpoints/test_orders.py:60: ValidationError","steps":[],"attachments":[{"uid":"8ad12af4f0ee3674","name":"log","source":"8ad12af4f0ee3674.txt","type":"text/plain","size":318},{"uid":"566444f19e7f8557","name":"stderr","source":"566444f19e7f8557.txt","type":"text/plain","size":314}],"parameters":[],"stepsCount":0,"attachmentsCount":2,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"story","value":"Change order status"},{"name":"feature","value":"Orders API"},{"name":"parentSuite","value":"tests.endpoints"},{"name":"suite","value":"test_orders"},{"name":"host","value":"fv-az654-267"},{"name":"thread","value":"2338-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.endpoints.test_orders"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"status","value":"'canceled'"},{"name":"x_task_value","value":"'api-18'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"2d1c196d4ca64ec8.json","parameterValues":["'canceled'","'api-18'"]}